version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tours-api
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=4000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tours_db
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - 4000:4000
    volumes:
      - ./:/app
      - /app/node_modules

  postgres:
    image: postgres:15
    container_name: tours-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tours_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: tours-pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    depends_on:
      - postgres

volumes:
  postgres_data:
